docs_dir: doc/book/ru
pages:
    - index.md
    - 'Тестирование приложений использущих doctrine/doctrine-orm-module': 'test-doctrine-app.md'
    - 'Блокировка инициализации функционала работы с консолью DoctrineORMModule': 'stop-doctrine-load-cli-post-event-listener.md'
    - 'Аггрегатор событий на основе конфига': 'callbacks-listener-aggregate.md'
    - 'Перегрузка конфигов приложения': 'override-app-config.md'

site_name: zf2-test-toolkit
site_description: 'Набор утилит для тестирования приложения на zf2'
repo_url: 'https://github.com/nnx-framework/zf2-test-toolkit'
copyright: 'Copyright (c) 2016 <a href="https://github.com/nnx-framework">NNX</a>'